### ISSUE TITLE
JSON.parse parser error

### ISSUE THREAD

**Issue by lukemadera** [nufyoot/createsend-node#6]
The JSON.parse failed and crashed our live server today. Potentially / probably bad return data from Campaign Monitor but we can't afford this crashing our server so wrap it in a try/catch like above? And/or check to ensure it's a JSON string before trying to parse?

https://github.com/nufyoot/createsend-node/blob/master/lib/interface/utils.js#L57

Error stack trace:
```js
SyntaxError: Unexpected token <
at Object.parse (native)
at Request._callback (/var/www/dropprice1/node_modules/createsend-node/lib/interface/utils.js:55:35)
at Request.self.callback (/var/www/dropprice1/node_modules/request/request.js:368:22)
at Request.EventEmitter.emit (events.js:98:17)
at Request.<anonymous> (/var/www/dropprice1/node_modules/request/request.js:1219:14)
at Request.EventEmitter.emit (events.js:117:20)
at IncomingMessage.<anonymous> (/var/www/dropprice1/node_modules/request/request.js:1167:12)
at IncomingMessage.EventEmitter.emit (events.js:117:20)
at _stream_readable.js:920:16
at /var/www/dropprice1/node_modules/newrelic/node_modules/continuation-local-storage/node_modules/async-listener/glue.js:188:31
```

**Comment by nufyoot** [comment]
Thanks for reporting this! I added a try catch for now. Do let me know if you see any other issues.

**Comment by lukemadera** [comment]
Great thanks @nufyoot
